// Code generated by Kitex v0.0.8. DO NOT EDIT.

package live

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"live/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddTxByID(ctx context.Context, Req *api.AddReq, callOptions ...callopt.Option) (r *api.BaseResp, err error)
	DeleteTxByID(ctx context.Context, Req *api.DeleteReq, callOptions ...callopt.Option) (r *api.BaseResp, err error)
	QueryTurnoverByRoomID(ctx context.Context, Req *api.QueryTurnoverByRoomIDReq, callOptions ...callopt.Option) (r *api.QueryTurnoverByRoomIDResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kLiveClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLiveClient struct {
	*kClient
}

func (p *kLiveClient) AddTxByID(ctx context.Context, Req *api.AddReq, callOptions ...callopt.Option) (r *api.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddTxByID(ctx, Req)
}

func (p *kLiveClient) DeleteTxByID(ctx context.Context, Req *api.DeleteReq, callOptions ...callopt.Option) (r *api.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteTxByID(ctx, Req)
}

func (p *kLiveClient) QueryTurnoverByRoomID(ctx context.Context, Req *api.QueryTurnoverByRoomIDReq, callOptions ...callopt.Option) (r *api.QueryTurnoverByRoomIDResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryTurnoverByRoomID(ctx, Req)
}
